name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Deploy
        run: |
          git config --global user.email "mevladyslav@gmail.com"
          git config --global user.name "this4you"
          npm run deploy
